stages:
  - test

variables:
  POSTGRES_DB: "AuthenticationService"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "password"
  DOCKER_DRIVER: overlay2

services:
  - name: docker:dind

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

test:
  stage: test
  script:
    - docker-compose -f docker-compose.yml -f docker-compose.ci.yml up -d
    - docker-compose -f docker-compose.yml -f docker-compose.ci.yml exec auth-service pytest
  only:
    - main