stages:
  - build
  - test
  - code-analysis
  - publish
  - deploy

build-job:
  stage: build
  script:
    - ./gradlew build -x test installFrontend

export-ui:
  stage: build
  script:
    - ./gradlew installNode
    - ./gradlew installPackageManager
    - ./gradlew installFrontend
    - ./gradlew export-ui


python-test:
  stage: test
  script:
    - ./gradlew pTest

java-test:
  stage: test
  script:
    - ./gradlew test

ui-test:
  stage: test
  script:
    - ./gradlew installNode
    - ./gradlew installPackageManager
    - ./gradlew installFrontend
    - ./gradlew jest


sonarscan:
  stage:
    code-analysis
  script:
    - echo "Linting code... This will take about 10 seconds."
    - ./gradlew sonar
    - echo "No lint issues found."


deploy-prod:
  stage: deploy
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
  environment: production
