build-job:
  stage: build
  tags:
      - linux  
  image:
      -gradle:7.6.4-jdk-17-alpine
  script:
    - ./gradlew build -x test

sonarscan:
  stage:
    test
  script:
    - echo "Linting code... This will take about 10 seconds."
    - ./gradlew sonarqube
    - echo "No lint issues found."


python-test:
  stage: test
  script:
    - ./gradlew pTest

java-test:
  stage: test
  script:
    - echo "This job tests something, but takes more time than test-job1."
    - echo "After the echo commands complete, it runs the sleep command for 20 seconds"
    - echo "which simulates a test that runs 20 seconds longer than test-job1"
    - sleep 20

ui-test:
  stage: test
  script:
    - echo "This job tests something, but takes more time than test-job1."
    - echo "After the echo commands complete, it runs the sleep command for 20 seconds"
    - echo "which simulates a test that runs 20 seconds longer than test-job1"
    - sleep 2

e2e-test:
  stage: test
  script:
    - ./gradlew e2eTest


deploy-prod:
  stage: deploy
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
  environment: production
