version: '3.9'

services:
#  web-ui:
#    build: ./frontend
#    ports:
#      - "3000:3000"
  zookeeper:
    build: external/zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
  kafka:
    build: ./external/kafka
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  neo4j:
    build: ./external/databases/neo4j
    ports:
      - 7474:7474
      - 7687:7687
    restart: unless-stopped
    environment:
      - NEO4J_AUTH=neo4j/password
    volumes:
      - ./external/databases/neo4j/db/data:/data
      - ./external/databases/neo4j/db/conf:/conf
      - ./external/databases/neo4j/db/logs:/logs
      - ./external/databases/neo4j/db/plugins:/plugins
  auth-service:
    build: ./services/auth/service
    ports:
      - "8081:81"
    depends_on:
      - auth-service-db
  auth-service-db:
    image: postgres:15-alpine
    volumes:
      - auth_postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: AuthenticationService
    ports:
      - "5432:5432"


volumes:
  auth_postgres_data: