version: '3.9'

services:
  auth-service:
    environment:
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - DATABASE_URL=postgresql://$POSTGRES_USER:$POSTGRES_PASSWORD@auth-service-db:5432/$POSTGRES_DB