server:
  servlet:
    context-path: "/geo-service"

spring:
  application:
    name: "geo-service"
  neo4j:
    uri: ${NEO4J-URI}
    authentication:
      username: ${NEO4J-USERNAME}
      password: ${NEO4J-PASSWORD}

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  otlp:
    collector_endpoint: ${otlp-collector-endpoint}
    metrics:
      export:
        url: ${otlp-metrics-url}
        step: 10s
    tracing:
      endpoint: ${otlp-tracing-endpoint}
  tracing:
    sampling:
      probability: 1.0
  metrics:
    distribution:
      percentiles:
        do.sleep.method.timed: 0.99, 0.95, 0.9, 0.7, 0.5
        http.server.requests: 0.99, 0.95, 0.9, 0.7, 0.5
      percentiles-histogram:
        do.sleep.method.timed: true
        http.server.requests: true
      minimum-expected-value:
        do.sleep.method.timed: 100ms
        http.server.requests: 100ms
      maximum-expected-value:
        do.sleep.method.timed: 10s
        http.server.requests: 10s
      slo:
        do.sleep.method.timed: 300ms,500ms,1s,2s
        http.server.requests: 300ms,500ms,1s,2s
