server:
  servlet:
    context-path: "/geo/api"

spring:
  kafka:
    bootstrap-servers: ${kafka-bootstrap-servers}
  neo4j:
    uri: ${neo4j-uri}
    authentication:
      username: ${neo4j-username}
      password: ${neo4j-password}
