server:
  port: 8090

spring:
  kafka:
    bootstrap-servers: localhost:29092
  cloud:
    gateway:
      routes:
        service1: http://localhost:8081
        service2: http://localhost:8082
        service3: http://localhost:8083

service_endpoints:
  auth: http://localhost:8080
