server:
  servlet:
    context-path: "/bff/api"

spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: 'http://localhost:3000'
            allowedHeaders: '*'
            allowedMethods:
              - GET
              - POST
      routes:
        - id: incident_service
          uri: ${incident-service-endpoint}/incident-service
          predicates:
            - Path=/incident-service/**
        - id: auth_service
          uri: ${auth-service-endpoint}/auth-service
          predicates:
            - Path=/auth-service/**
        - id: communication_service
          uri: ${communication-service-endpoint}/communication-service
          predicates:
            - Path=/communication-service/**
        - id: geo_service
          uri: ${geo-service-endpoint}/geo-service
          predicates:
            - Path=/geo-service/**
        - id: gen_ai_service
          uri: ${gen-ai-service-endpoint}/gen-ai-service
          predicates:
            - Path=/gen-ai-service/**

service_endpoints:
  auth: "${auth-service-endpoint}"

springdoc:
  api-docs:
    path: "/api-docs"
  swagger-ui:
    path: "/swagger-ui-bff.html"

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
#zuul:
#  host:
#    socket-timeout-millis: 100000
#  ribbon:
#    eager-load:
#      enabled: true
#  routes:
#    test:
#      url: http://localhost:8001
#  ssl-hostname-validation-enabled: false
