server:
  port: 8090

spring:
  kafka:
    bootstrap-servers: localhost:29092

service_endpoints:
  auth: http://localhost:8080

management:
  otlp:
    collector_endpoint: http://localhost:4317
    metrics:
      export:
        url: http://localhost:4318/v1/metrics
    tracing:
      endpoint: http://localhost:4318/v1/traces
