global:
  scrape_interval: 10s
  evaluation_interval: 10s

remote_write:
  - url: http://mimir:9009/api/v1/push

scrape_configs:
  - job_name: "otel-collector"
    static_configs:
      - targets: ["otel-collector:8889"]
