server:
  port: 8074

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password
  liquibase:
    change-log: classpath:liquibase/local-changelog.xml
  kafka:
    bootstrap-servers: localhost:29092
  neo4j:
    uri: neo4j://localhost:7687
    authentication:
      username: neo4j
      password: password
