server:
  port: 8092

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password
  liquibase:
    change-log: classpath:liquibase/local-changelog.xml
