# Default values for geoservice-neo4j.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

service:
  type: ClusterIP
  port: 7687
  targetPort: 7687

neo4j:
  passwordFromSecret: neo4j-password
  password: ""

image:
  customImage: "mathisntcd/cdm-neo4j:latest"
  pullPolicy: "Always"
