# Default values for geoservice-neo4j.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

  nameOverride: geoservice-neo4j

  fullnameOverride: geoservice-neo4j

service:
  type: ClusterIP
  port: 7687
  targetPort: 7687
  # Optionally, specify a service name if needed
  # name: neo4j-service

neo4j:
  # Set to use password from Kubernetes Secret
  # Ensure the secret 'neo4j-password' exists and has a key 'neo4j-password'
  passwordFromSecret: "neo4j-password"
  # Since password is from a secret, leave this empty
  password: ""

  edition: "community"
  # If you're using Neo4j Community edition, acceptLicenseAgreement is not needed
  # For Enterprise edition, you must accept the license agreement
  # edition: "community"
  # acceptLicenseAgreement: "yes"


image:
  imagePullPolicy: Always
  # set a customImage if you want to use your own docker image
  customImage: mathisntcd/cdm-neo4j:latest

volumes:
  data:
    #labels for data pvc on creation (Valid only when mode set to selector | defaultStorageClass | dynamic | volumeClaimTemplate)
    labels: { }
    #Set it to true when you do not want to use the subPathExpr
    disableSubPathExpr: false
    # REQUIRED: specify a volume mode to use for data
    # Valid values are share|selector|defaultStorageClass|volume|volumeClaimTemplate|dynamic
    mode: "defaultStorageClass"
