server:
  port: 8096

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password
  liquibase:
    change-log: classpath:liquibase/local-changelog.xml
endpoints:
  communication: http://localhost:8090/communication-service
  geoservice: http://localhost:8090/geo-service