server:
  port: 8096

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password
  liquibase:
    change-log: classpath:liquibase/local-changelog.xml
endpoints:
  communication: localhost:8080/communication-service
  geoservice: localhost:8080/geo-service